In [43]:
import numpy as np 
import matplotlib as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [116]:
#importing the dataset and defining the dependent and independent variables
dataset = pd.read_csv("E:\Capstone G3 Sources\Model Training Data2.csv")
X = dataset.iloc[:,:-1]
y = dataset.iloc[:,4]
dataset

Day Temperature C  Night Temperature C  Humidity   Soil pH  \
0                23.0                 17.0         70     7.00   
1                23.9                 17.0         70     7.00   
2                24.8                 17.0         70     7.00   
3                25.7                 17.0         70     7.00   
4                26.6                 17.0         70     7.00   
..                ...                  ...        ...      ...   
94               23.0                 17.6         58     6.50   
95               28.3                 17.0         90     6.67   
96               30.0                 18.0         80     7.26   
97               23.9                 16.0         75     7.00   
98               21.2                 19.2         55     6.30   

    Amount of fruit per plant kg  
0                         15.000  
1                         14.750  
2                         14.500  
3                         14.250  
4                         14.000  
..                           ...  
94                        14.125  
95                        13.750  
96                        13.750  
97                        14.125  
98                        12.987  

[99 rows x 5 columns]

In [117]:
#splitting the data for training and testing and putting it into arrays the model can interpret
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)
y_test

array([13.75 , 13.75 , 13.875, 14.75 , 14.   , 13.75 , 14.75 , 14.5  ,
       13.   , 13.   , 14.125, 14.   , 14.375, 14.   , 14.625, 13.25 ,
       14.   , 14.25 , 14.25 , 14.125, 14.125, 14.125, 14.   , 14.   ,
       13.5  ])

In [68]:
X_test.shape

(25, 4)

In [118]:
#reshaping all the data arrays into 2D arrays
np.reshape(X_train, (-1, 296))
np.reshape (y_train, (-1, 74))
np.reshape (X_test, (-1, 25))
np.reshape (y_test, (-1, 25))

array([[13.75 , 13.75 , 13.875, 14.75 , 14.   , 13.75 , 14.75 , 14.5  ,
        13.   , 13.   , 14.125, 14.   , 14.375, 14.   , 14.625, 13.25 ,
        14.   , 14.25 , 14.25 , 14.125, 14.125, 14.125, 14.   , 14.   ,
        13.5  ]])

In [127]:
#training the model with the training data
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [100]:
#reshaping the first results into 2D array
y_predict = regressor.predict(X_test)
np.reshape (y_predict, (-1, 25))

array([[13.84204127, 14.08973494, 13.78971675, 14.27720015, 14.28679004,
        14.07937338, 14.17896113, 14.29119622, 14.16464103, 13.78510397,
        14.01981272, 13.83826195, 13.99609424, 14.21255514, 14.24265102,
        13.88664762, 14.00531891, 14.03082818, 14.1855704 , 14.05386411,
        14.02279271, 13.93454507, 14.40673596, 13.93373777, 13.98309027]])

In [76]:
len(y_predict)

1

In [128]:
#finding R2 to determine the accuracy of the predictions
import sklearn.metrics as sm
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_predict), 2)) 
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_predict), 2)) 
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_predict), 2)) 
print("Explain variance score =", round(sm.explained_variance_score(y_test, y_predict), 2)) 
print("R2 score =", round(sm.r2_score(y_test, y_predict), 2))

Mean absolute error = 0.31
Mean squared error = 0.17
Median absolute error = 0.22
Explain variance score = 0.2
R2 score = 0.18


In [98]:
#testing new data on the model
result1 = regressor.predict([[21, 19, 55, 6]])
result1

array([13.81330993])